### ISSUE TITLE
Can't connect to audio

### ISSUE THREAD

**Issue by aronkvh** [NickvisionApps/Cavalier#100]
2023.8.1 just displays the new "Let's dance!" screen
terminal shows no errors:
_[AURA] Listening to commands.

(NickvisionCavalier.GNOME:2): Gtk-CRITICAL **: 00:46:29.876: gtk_widget_get_parent: assertion 'GTK_IS_WIDGET (widget)' failed

(NickvisionCavalier.GNOME:2): Gtk-CRITICAL **: 00:46:29.883: gtk_widget_add_css_class: assertion 'GTK_IS_WIDGET (widget)' failed_

Fresh install on KDE neon 5.27, Plasma 5.27.6 
Kernel Version: 5.19.0-50-generic (64-bit)
pulseaudio permission is granted

**Comment by fsobolev** [comment]
Flatpak or snap?

**Comment by fsobolev** [comment]
I managed to reproduce it with flatpak in Lubuntu VM.
Could you confirm that the app works fine with `CAVALIER_INPUT_METHOD=pulse`?

**Comment by aronkvh** [comment]
If I `flatpak run org.nickvision.cavalier CAVALIER_INPUT_METHOD=pulse` it's still not working

**Comment by fsobolev** [comment]
> If I `flatpak run org.nickvision.cavalier CAVALIER_INPUT_METHOD=pulse` it's still not working

Sorry, I should have provided you with a correct full command:

`flatpak run --env=CAVALIER_INPUT_METHOD=pulse org.nickvision.cavalier`

**Comment by aronkvh** [comment]
Of course, I forgot the env part. 
Now it runs, even though the automatic sensitivity messes it up, after adjusting it manually it works well :)

**Comment by fsobolev** [comment]
I will revert to using PulseAudio by default in next version then.
The temporary workaround is to use this env var (or snap package).
