### ISSUE TITLE
Main menu button doesn't work

### ISSUE THREAD

**Issue by gregorni** [NickvisionApps/Cavalier#125]
Clicking on the main menu button in the top left doesn't open the menu.

I'm on Fedora 38 and am using the latest Flatpak from Flathub.

**Comment by fsobolev** [comment]
Hm... I didn't have this problem yesterday when I was on Fedora Silverblue 38, and I don't have the problem now on Arch... No idea what can cause this.

**Comment by gregorni** [comment]
Hmm, maybe it's a temporary issue on my end. I'll try again next time I turn on my computer

**Comment by gregorni** [comment]
No, I still have the problem. Cavalier is also the only app where I it appears.

**Comment by nlogozzo** [comment]
Could you send a screen recording of you trying to do it...just so we can see how it's setup and looks. 

Also, are you using Wayland or X11?

**Comment by gregorni** [comment]
I'm on GNOME 44 on Wayland

[Screencast from 2023-09-28 16-55-58.webm](https://github.com/NickvisionApps/Cavalier/assets/119804311/7ddd53d4-6ffb-4007-b896-b7621b5ec794)

**Comment by nlogozzo** [comment]
Ok well in the mean time you should be able to toggle the menu using `F10` keyboard shortcut. Let me know if that works...

And access Preferences with `Ctrl+,`

**Comment by gregorni** [comment]
`F10` also doesn't work, `Ctrl+,` does.

**Comment by nlogozzo** [comment]
> F10 also doesn't work

Weird...will look into it

> Ctrl+, does.

Ok that's good at least

**Comment by nlogozzo** [comment]
Hi @gregorni ,

just wondering...maybe some gtk flatpak update fixed this...does this issue still occur?

I will try updating the app to GNOME 45 runtime as well and see if that would solve this issue for you too.

**Comment by gregorni** [comment]
The issue no longer occurs for me (I'm now on Universal Blue silverblue-main:39)
