### ISSUE TITLE
Missing file when attempting to build package

### ISSUE THREAD

**Issue by Akaimana** [NickvisionApps/Cavalier#133]
Hello,
When I used makepkg, an error occured in build() when executing 'publish' - the following file couldn't be found:
` /home/me/cavalier/src/cavalier/NickvisionCavalier.Shared/org.nickvision.cavalier.in`
Using a file manager, I can confirm it wasn't directly there. However, I found the required file within `NickvisionCavalier.Shared/Linux`. After copying it to the expected location, the package was made without error. 

I'm new to Linux, so I was wondering if this was as fault of mine or a bug.

**Comment by nlogozzo** [comment]
What was the script you use? If you used the one from AUR, it is out of data and needs to be updated to support V2023.11.0 (which is what introduced that change)

**Comment by Akaimana** [comment]
Yes, I believe I used `git clone https://aur.archlinux.org/cavalier.git` 
That would make sense. Thank you!
