### ISSUE TITLE
allow setting colors from cli or file

### ISSUE THREAD

**Issue by exoess** [NickvisionApps/Cavalier#137]
allowing setting colors from the cli or a file would be really useful, having to edit the colors from prefs is annoying, it completely prevents you from doing it dynamically (which is rather limiting). please add this, thanks :)

**Comment by nlogozzo** [comment]
In the version being released today, you will be able to use `--fg aarrggbb`, `--fg rrggbb`, `--bg aarrggbb`, and `--bg rrggbb` to set the foreground and background hex colors via CLI respectively

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Cavalier/releases/tag/2024.1.0

**Comment by nlogozzo** [comment]
1. Make sure you're using version 2024.1.0
2. Run Cavalier normally from the desktop, i.e. have an instance already running, and then modify it from the command line with `cavalier --bg rrggbb`

**Comment by exoess** [comment]
ahhh, i see

**Comment by exoess** [comment]
but why not allow them to be passed into it at launch?

**Comment by nlogozzo** [comment]
> but why not allow them to be passed into it at launch?

The CLI interface is meant to be used to modify your existing Cavalier instance. 

If no instance is running, there is nothing to modify.

Think of it as you can't open the Preference dialog in the GUI itself, without opening the app first (just FYI all of the modifications that can be made via CLI are also found in the Preferences dialog). 

Same concept.

**Comment by exoess** [comment]
i see, thanks
