### ISSUE TITLE
Audio thread exited unexpectedly. input/pulse.c: Could not open pulseaudio source:

### ISSUE THREAD

**Issue by BegoneRaven** [NickvisionApps/Cavalier#148]
Installed Cavalier 2024.1.0 as an Ubuntu Snap
Ubuntu version : 22.04.3 LTS 
I've got no problems playing audio using VLC or a browser

But, when launching up 'cavalier' from the command line, I get the following error
```
[AURA] Listening to commands.
Audio thread exited unexpectedly. input/pulse.c: Could not open pulseaudio source: alsa_output.pci-0000_00_0e.0.analog-stereo.monitor, Access denied.                 To find a list of your pulseaudio sources run 'pacmd list-sources'
```
Any help appreciated!

**Comment by nlogozzo** [comment]
@soumyaDghosh seems like a snap issue

**Comment by soumyaDghosh** [comment]
@fsobolev You installed pipewire-pulse right? to fix it? 

Can you give that a try @BegoneRaven?

`sudo apt install pipewire-pulse`
