### ISSUE TITLE
[Actions Failure] GNOME on Flatpak fails

### ISSUE THREAD

**Issue by ForceConstant** [NickvisionApps/Cavalier#163]
I noticed that your github workflow action for flatpak has been failing for at least the last 4 months. with the following errors. 

 GNOME on Flatpak (x86_64)
Build failed: Error: The process '/usr/bin/xvfb-run' failed with exit code 1

https://github.com/NickvisionApps/Cavalier/actions/runs/8491918705

@DaPigGuy

**Comment by nlogozzo** [comment]
It's due to not updating the nuget dependencies.

Cavalier is on my list to be rewritten from C# to C++ so that will all be fixed once that happens.
