### ISSUE TITLE
Missing resources in flathub beta build

### ISSUE THREAD

**Issue by rene-coty** [NickvisionApps/Cavalier#20]
It seems that 'foreground' and 'background' icons are missing

![Capture d’écran du 2023-07-02 10-19-32](https://github.com/NickvisionApps/Cavalier/assets/95506494/90459b80-4250-496b-9163-13e2739373a4)

org.nickvision.cavalier
2023.7.0-beta1
GTK 4.10.3
libadwaita 1.3.2
Flatpak
fr-FR
LANG=fr_FR.UTF-8
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=

**Comment by fsobolev** [comment]
Fixed in https://github.com/NickvisionApps/Cavalier/commit/8268a88f1da1c8daf40e5c528462905b6f85411a
Flathub update will be available soon.
