### ISSUE TITLE
Only reverse one mirror

### ISSUE THREAD

**Issue by Suyashtnt** [NickvisionApps/Cavalier#29]
It would be nice that if you had mirror set to `full` or `split channels` you could reverse one of the mirrors but not the other. It looks quite cool in other visualizers I've used that support it.

**Comment by fsobolev** [comment]
I don't quite understand, could you show an example?

**Comment by Suyashtnt** [comment]
> I don't quite understand, could you show an example?
something like <https://steamcommunity.com/sharedfiles/filedetails/?id=904034085>. The bottom half is reversed compared to the top half

**Comment by fsobolev** [comment]
> The bottom half is reversed compared to the top half

Well, I can add option to basically do this:

![image](https://github.com/NickvisionApps/Cavalier/assets/117388856/498bd027-68ae-43cd-8b7d-3572370e0c87)

(not the best screenshot probably 😅 )

As for "Sound Splitter", I think a new drawing mode that looks like it will be great!

**Comment by Suyashtnt** [comment]
> > The bottom half is reversed compared to the top half
> 
> Well, I can add option to basically do this:
> 
> ![image](https://user-images.githubusercontent.com/117388856/253276738-498bd027-68ae-43cd-8b7d-3572370e0c87.png)
> 
> (not the best screenshot probably 😅 )
> 
> As for "Sound Splitter", I think a new drawing mode that looks like it will be great!

Hmm, this doesn't look like exactly what I wanted. It's more like the reverse thing is only applied to the bottom half of it. That's what I would like if it's possible. But if it isn't what you sent seems close enough :)
