### ISSUE TITLE
desktop file set category for application menu

### ISSUE THREAD

**Issue by Renner0E** [NickvisionApps/Cavalier#32]
On KDE cavalier (flatpak) is placed in the "Lost & Found" category by default.
I think it should be placed in "Utilities"

I haven't figured out how to add a category yet because the `Categories=` line is missing in the desktop file in this repo. But when you install the app the `Categories=GTK;` line is magically there ;)
This is why this isn't just a merge request. 

Is it possible to change the Categories when you build it?

The line must be `Categories=GTK;Audio;Utility;`

Have a nice day.

**Comment by fsobolev** [comment]
> But when you install the app the Categories=GTK; line is magically there ;)

Huh, magic indeed, maybe flatpak adds it automatically?

I don't think the app fits `Utility` category, but I will add `GTK;AudioVideo;Audio`, thanks

**Comment by Renner0E** [comment]
That's fine with me, thanks.
