### ISSUE TITLE
Find a way to make rounded items less pixelated

### ISSUE THREAD

**Issue by fsobolev** [NickvisionApps/Cavalier#45]
![](https://github.com/NickvisionApps/Cavalier/assets/117388856/98cf98f3-0c36-4643-9e6b-abd6270ebcb7)

New Cavalier on the left, old one on the right. I guess it's the cost of using faster but less accurate Skia.

Maybe when roundness > 0 blur the image just a little?

**Comment by Suyashtnt** [comment]
> ![](https://user-images.githubusercontent.com/117388856/255349408-98cf98f3-0c36-4643-9e6b-abd6270ebcb7.png)
> 
> New Cavalier on the left, old one on the right. I guess it's the cost of using faster but less accurate Skia.
> 
> Maybe when roundness > 0 blur the image just a little?

Is there no AA or similar in GTK?

**Comment by fsobolev** [comment]
> Is there no AA or similar in GTK?

This is not drawn by GTK, but by SkiaSharp. I know there's blur filter that can be added but I will also look for other solutions.
