### ISSUE TITLE
Visualizer only fills half of the window with 200% display scaling

### ISSUE THREAD

**Issue by timas130** [NickvisionApps/Cavalier#74]
GNOME 44.3 on Wayland, Arch Linux, Cavalier 2023.8.0 from Flathub.

The vizualizer fills only half of the window from the bottom left, everything else is transparent. This only happens on >200% display scaling.

<details>
<summary>Screenshot</summary>

![Screenshot](https://github.com/NickvisionApps/Cavalier/assets/20511387/e3428aac-18b0-4486-bc87-35685b77a603)

</details>

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Cavalier/releases/tag/2023.8.1-rc1
