### ISSUE TITLE
Suggestion: Colors on either side of "splitter"

### ISSUE THREAD

**Issue by rexendevar** [NickvisionApps/Cavalier#85]
I think it would be cool to set a color for either side of a splitter - this could be used to create a distinct separation to fit a color scheme where no part of the screen is more obscured than any other when using transparency in the colors.

**Comment by fsobolev** [comment]
I don't get it, sorry... Could you maybe make a drawing showing where you want to change color?

**Comment by rexendevar** [comment]
https://media.discordapp.net/attachments/419703257355517967/1137822644964691998/image.png i hope this makes it clear but i can understand why it might not lol

**Comment by fsobolev** [comment]
I decided to not overwhelm the app with one more setting, especially with specific to just one mode. What you want to do can be achieved with an image and gradients: you can set the same image for background and foreground, decrease alpha to make images half-transparent and add a color or a gradient to be mixed with images.

![image](https://github.com/NickvisionApps/Cavalier/assets/117388856/45526a7d-1d1f-4720-80bf-50d62a93f64b)
