### ISSUE TITLE
Suggestion: foreground image instead of color (transparency gradient?)

### ISSUE THREAD

**Issue by rexendevar** [NickvisionApps/Cavalier#86]
I think it would be awesome to set a visualizer up so you have, for instance, a nighttime scene as the background image, but a daytime version of the same shot comes in in the shape of a wave. This would be especially cool if you can use a gradient of  transparency. I've done a mockup: https://media.discordapp.net/attachments/419703257355517967/1137820343323594813/image.png This depicts a background image with an altered version of itself used as a foreground image. It is also set to use a gradient between fully transparent at the base and fully opaque at the tips.

**Comment by fsobolev** [comment]
This will probably do to 2023.8.2/2023.9.0 because this will require to change renderer a lot.
