### ISSUE TITLE
Suggestion: Option to rotate circle visualizer

### ISSUE THREAD

**Issue by rexendevar** [NickvisionApps/Cavalier#87]
I was making a visualizer for a song a while ago and I realized that just being able to move the visualizer around, while cool, is not enough. Refer to the following image: https://media.discordapp.net/attachments/419703257355517967/1137823450392703006/image.png

I would like to center the visualizer circle around the bird that's approximately in the middle. However, there is a very distinct line of symmetry in both the visualizer and the bird, and they are at different angles. I would like to be able to rotate the visualizer to better align these two.

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/Cavalier/releases/tag/2023.8.1-rc1
